### ISSUE TITLE
AttributeError: 'Finvoice' object has no attribute 'to_etree'

### ISSUE THREAD

**Issue by oerp-odoo** [codemasteroy/py-finvoice#2]
I get an error when trying to use this (testing with finvoice example from https://wiki.xmldation.com/General_Information/e-Invoice):

``` python
from finvoice import finvoice
tree = finvoice.parseEtree('Finvoice201_wo_SOAP_example.xml', silence=True)
```

``` python
Traceback (most recent call last):
  File "finvoice-test.py", line 4, in <module>
    tree = finvoice.parseEtree('Finvoice201_wo_SOAP_example.xml', silence=True)
  File "/usr/local/lib/python2.7/dist-packages/finvoice/finvoice.py", line 18530, in parseEtree
    rootElement = rootObj.to_etree(None, name_=rootTag, mapping_=mapping)
AttributeError: 'Finvoice' object has no attribute 'to_etree'
```

P.S. Downloaded your module with pip.

**Comment by mohanjith** [comment]
Please use parse method. Since the XML file is v2.01import finvoice201 for better compatibility.

Thanks!

**Comment by oerp-odoo** [comment]
Is there some helper method to convert returned object (using parse method) to for example dictionary? Or should I just use `__dict__` for every object's attribute?

**Comment by mohanjith** [comment]
Yep, **dict** should do the trick in most cases.

Let me know how it goes, specially if you get stuck. 

Patches and pull requests are welcome as well :)
